### ISSUE TITLE
Some error for the Cat example

### ISSUE THREAD

**Issue by lamerman** [backuity/clist#10]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: scala.runtime.ObjectRef.create(Ljava/lang/Object;)Lscala/runtime/ObjectRef;
        at org.backuity.clist.Command.read(Command.scala:12)
        at org.backuity.clist.Parser$$anonfun$withCommand$1.apply(Parser.scala:130)
        at org.backuity.clist.Parser$$anonfun$withCommand$1.apply(Parser.scala:129)
        at org.backuity.clist.Parser.withParsingException(Parser.scala:167)
        at org.backuity.clist.Parser.withCommand(Parser.scala:129)
        at com.xxx.CatDemo$.main(Pig.scala:16)
        at com.xxx.CatDemo.main(Pig.scala)
        ... 6 more

    <properties>
        <scala.version>2.11.8</scala.version>
    </properties>

    <dependency>
      <groupId>org.backuity.clist</groupId>
      <artifactId>clist-core_2.11</artifactId>
      <version>2.0.2</version>
    </dependency>

    <dependency>
      <groupId>org.backuity.clist</groupId>
      <artifactId>clist-macros_2.11</artifactId>
      <version>2.0.2</version>
    </dependency>

**Comment by backuitist** [comment]
Works for me. Do you have a repo on github that demonstrates the bug?

**Comment by lamerman** [comment]
No, I don't have a repo on github that demonstrates the bug.

**Comment by backuitist** [comment]
Well, until then I'm closing this. Try a `mvn clean install`.
